#spring.application.name=JPP-3.1.4
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=create-drop

spring:
  application:
    name:
      JPP-3.1.4

  datasource:
    driver-class-name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/test_db
    username:
      postgres
    password:
      root

  jpa:
    show-sql:
      false
    hibernate:
      ddl-auto:
        create-drop